services:
  db:
    image: mysql:8.0docker compose up -d
  ./mvnw spring-boot:run
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: anime
    ports:
      - "3306:3306"
    volumes:
      - devdojo_data:/var/lib/mysql

volumes:
  devdojo_data: